# Atom IDE Dependency Policy

[licenses]
# Allow only permissive licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]

# Deny copyleft licenses
deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "LGPL-2.1",
    "LGPL-3.0",
    "AGPL-3.0",
]

confidence-threshold = 0.8
exceptions = []

[bans]
# Deny multiple versions of same crate 
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"

# Explicitly ban mock-related crates
deny = [
    # Mock testing frameworks (banned by ANTI-MOCK policy)
    { name = "mockall" },
    { name = "wiremock" },
    { name = "httpmock" },
    { name = "mockito" },
    { name = "fake" },
    
    # Other security-sensitive crates to avoid
    { name = "openssl", use-instead = "rustls" },
]

# Skip certain crates that commonly have multiple versions
skip = [
    { name = "windows_x86_64_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "redox_syscall" },
]

skip-tree = []

[advisories]
# Deny security vulnerabilities
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "deny"
notice = "warn"

ignore = []

[sources]
# Only allow crates.io and git
unknown-registry = "deny"
unknown-git = "deny"

allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []