# Atom IDE Formatting Rules
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
format_strings = false